### ISSUE TITLE
[Suggestion] - Add `requirements.txt`

### ISSUE THREAD

**Issue by transcental** [SpaceFace02/Compendium_ML_Projects#1]
Instead of having the user read through all of the imports or the error logs, maybe just add a `requirements.txt` in each project with the requirements. Then the user can just run the following commands instead of having to comb through trying to make sure they've got everything.

```
python -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python file.py
```

*I'm a bit busy atm, but if this is still open in a week or so and I remember, I'll create a PR*

**Comment by SpaceFace02** [comment]
Yeah, it's a really good suggestion, will start working on it soon.
